'use client';
import { useState } from 'react';
import { Share2, Save, Clock, Download, Check } from 'lucide-react';
import type { RREFResult } from '@/lib/calculators/shared-types';
import type { HistoryEntry, SavedProblem } from '@/lib/calculators/shared-types';
import { encodeMatrixToUrl } from '@/lib/calculators/rref';
import { matrixToLatex } from '@/lib/calculators/rational';

interface SaveShareBarProps {
  rawMatrix: string[][];
  rows: number;
  cols: number;
  isAugmented: boolean;
  result: RREFResult | null;
  history: HistoryEntry[];
  onLoadHistory: (entry: HistoryEntry) => void;
}

export default function SaveShareBar({
  rawMatrix,
  rows,
  cols,
  isAugmented,
  result,
  history,
  onLoadHistory,
}: SaveShareBarProps) {
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [saveName, setSaveName] = useState('');
  const [showSaveDialog, setShowSaveDialog] = useState(false);

  const handleShare = () => {
    const encoded = encodeMatrixToUrl(rawMatrix, rows, cols, isAugmented);
    const url = `${window.location.origin}/?m=${encoded}`;
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleSave = () => {
    if (!saveName.trim()) return;
    const saved: SavedProblem = {
      id: Date.now().toString(),
      name: saveName.trim(),
      matrix: rawMatrix,
      rows,
      cols,
      isAugmented,
      savedAt: Date.now(),
    };
    const existing: SavedProblem[] = JSON.parse(localStorage.getItem('rref_saved') || '[]');
    existing.unshift(saved);
    localStorage.setItem('rref_saved', JSON.stringify(existing.slice(0, 20)));
    setSaveName('');
    setShowSaveDialog(false);
  };

  const handleExportLatex = () => {
    if (!result) return;
    const original = matrixToLatex(result.originalMatrix, isAugmented);
    const rref = matrixToLatex(result.rrefMatrix, isAugmented);
    const stepsLatex = result.steps.map((s, i) =>
      `\\text{Step ${i + 1}: } ${s.latex} \\\\\n${matrixToLatex(s.matrix, false)}`
    ).join('\n\n');

    const full = `% RREF Solution — Generated by RREF Calculator\n\\[\n\\text{Original: } ${original}\n\\]\n\n${stepsLatex}\n\n\\[\n\\text{RREF: } ${rref}\n\\]`;
    const blob = new Blob([full], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'rref_solution.tex';
    a.click();
  };

  return (
    <div className="border-t border-slate-100 pt-3 mt-1">
      <div className="flex flex-wrap items-center gap-2">
        <button
          onClick={handleShare}
          className="btn-ghost flex items-center gap-1.5"
          title="Copy shareable link"
        >
          {copied ? <Check size={14} className="text-accent-green" /> : <Share2 size={14} />}
          {copied ? 'Copied!' : 'Share'}
        </button>

        <button
          onClick={() => setShowSaveDialog(!showSaveDialog)}
          className="btn-ghost flex items-center gap-1.5"
        >
          <Save size={14} />
          Save
        </button>

        {result && (
          <button
            onClick={handleExportLatex}
            className="btn-ghost flex items-center gap-1.5"
          >
            <Download size={14} />
            Export LaTeX
          </button>
        )}

        {history.length > 0 && (
          <button
            onClick={() => setShowHistory(!showHistory)}
            className="btn-ghost flex items-center gap-1.5 ml-auto"
          >
            <Clock size={14} />
            History ({history.length})
          </button>
        )}
      </div>

      {showSaveDialog && (
        <div className="mt-2 flex gap-2">
          <input
            type="text"
            value={saveName}
            onChange={e => setSaveName(e.target.value)}
            placeholder="Problem name..."
            className="flex-1 border border-slate-200 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
            onKeyDown={e => e.key === 'Enter' && handleSave()}
            autoFocus
          />
          <button onClick={handleSave} disabled={!saveName.trim()} className="btn-primary text-sm px-3 py-1.5">
            Save
          </button>
          <button onClick={() => setShowSaveDialog(false)} className="btn-secondary text-sm px-3 py-1.5">
            Cancel
          </button>
        </div>
      )}

      {showHistory && (
        <div className="mt-3 border border-slate-200 rounded-lg overflow-hidden">
          <div className="bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600 uppercase tracking-wide border-b border-slate-200">
            Recent History
          </div>
          <div className="divide-y divide-slate-100 max-h-48 overflow-y-auto">
            {history.map(entry => (
              <button
                key={entry.id}
                onClick={() => {
                  onLoadHistory(entry);
                  setShowHistory(false);
                }}
                className="w-full text-left px-3 py-2 hover:bg-slate-50 transition-colors"
              >
                <div className="text-xs font-mono text-slate-700">
                  {entry.rows}×{entry.cols} matrix{entry.isAugmented ? ' (augmented)' : ''}
                </div>
                <div className="text-xs text-slate-400">
                  Rank {entry.rank} · {new Date(entry.solvedAt).toLocaleTimeString()}
                </div>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
